// pathofexile.com/trade query building, shared by the UI (which turns queries into
// clickable search links) and scripts/price.ts (which runs them against the trade
// API to cache prices). Both must build the *identical* query — a price cached for
// a different search than the link opens would be quietly wrong — so this is the
// single place either one constructs a query.
//
// Trade stat ids come from data/trade-stats.json (generated by
// scripts/build-trade-stats.mjs from the trade site's stat list):
// clusterTypeOptions maps each cluster type to its enchant option id, and
// notableExplicits maps each notable to its "1 Added Passive Skill is X"
// explicit stat id.

import tradeStats from './data/trade-stats.json'

export const PASSIVE_COUNT_STAT = 'enchant.stat_3086156145' // "Adds # Passive Skills"
export const CLUSTER_TYPE_STAT = 'enchant.stat_3948993189' // "Added Small Passive Skills grant: #"
export const SMALL_PASSIVE_EFFECT_STAT = 'explicit.stat_2618549697' // "Added Small Passive Skills have #% increased Effect"

// Cluster type text -> trade enchant option id. Two-line grants (large jewels)
// appear in our data as "A / B" but the trade site joins the lines with a space.
const enchantOptionByText: Record<string, string> = tradeStats.clusterTypeOptions
export const clusterTypeOption = (clusterType: string): string | undefined =>
  enchantOptionByText[clusterType] ?? enchantOptionByText[clusterType.replaceAll(' / ', ' ')]

// Notable name -> explicit stat id.
const explicitIdByNotable: Record<string, string> = tradeStats.notableExplicits

export interface ComboCount {
  combo: string
  notables: string[]
  count: number
  passivesMin: number | null
  passivesMax: number | null
}

// "35% increased Small Passive Effect" is our display text for the numeric explicit
// "Added Small Passive Skills have 35% increased Effect". It rides along in the
// notables list but isn't a notable, so most logic here has to tell them apart.
const EFFECT_RE = /^(\d+)% increased Small Passive Effect$/
export const effectPercent = (notable: string): number | null => {
  const m = EFFECT_RE.exec(notable)
  return m ? Number(m[1]) : null
}

export interface PassiveRange {
  min: number | null
  max: number | null
}

// Which "Adds # Passive Skills" roll to search for. The passive count observed in
// our snapshot is only a fallback: for the combos people actually shop for there's
// one specific roll worth buying, and searching the observed spread instead would
// surface jewels nobody wants. Effect-mod rules are checked before notable-count
// rules, so a large jewel carrying both pins to 12.
export function pinnedPassives(
  base: string,
  notables: string[],
  observedMin: number | null,
  observedMax: number | null,
): PassiveRange {
  const effect = notables.map(effectPercent).find((p) => p != null)
  const notableCount = notables.filter((n) => effectPercent(n) == null).length

  switch (base) {
    case 'Large Cluster Jewel':
      // The increased-effect mod is only worth its slot on a 12-passive jewel;
      // otherwise 3 notables means the cheap 8-passive roll.
      if (effect != null) return { min: 12, max: 12 }
      if (notableCount >= 3) return { min: 8, max: 8 }
      break
    case 'Medium Cluster Jewel':
      if (effect != null) return { min: 4, max: 5 }
      if (notableCount >= 2) return { min: 4, max: 5 }
      break
    case 'Small Cluster Jewel':
      if (effect != null && effect >= 25 && effect <= 35) return { min: 3, max: 3 }
      break
  }
  return { min: observedMin, max: observedMax }
}

export interface TradeQuery {
  query: {
    status: { option: string }
    type: string
    filters: Record<string, unknown>
    stats: object[]
  }
  sort: { price: string }
}

// Every search excludes corrupted jewels — a corrupted one can't be crafted on or
// modified, so it isn't comparable to the rest of the listings.
const uncorrupted = { misc_filters: { filters: { corrupted: { option: 'false' } } } }

const statFilter = (option: string, passives: PassiveRange): object[] => {
  const filters: object[] = []
  if (passives.min != null && passives.max != null)
    filters.push({ id: PASSIVE_COUNT_STAT, value: { min: passives.min, max: passives.max } })
  filters.push({ id: CLUSTER_TYPE_STAT, value: { option } })
  return filters
}

// Trade query for one observed combo: base type + passive count + cluster type
// enchant + one explicit filter per notable. Returns null if any part can't be
// resolved to a trade stat id (better no search than a wrong one).
export function buildComboQuery(
  base: string,
  clusterType: string,
  cc: ComboCount,
): TradeQuery | null {
  if (cc.notables.length === 0) return null
  const option = clusterTypeOption(clusterType)
  if (!option) return null

  const passives = pinnedPassives(base, cc.notables, cc.passivesMin, cc.passivesMax)
  const filters = statFilter(option, passives)
  for (const n of cc.notables) {
    const pct = effectPercent(n)
    if (pct != null) {
      filters.push({ id: SMALL_PASSIVE_EFFECT_STAT, value: { min: pct, max: pct } })
      continue
    }
    const id = explicitIdByNotable[n]
    if (!id) return null
    filters.push({ id, value: { min: 1, max: 1 } })
  }

  return {
    query: {
      status: { option: 'securable' },
      type: base,
      filters: { ...uncorrupted },
      stats: [{ type: 'and', filters, disabled: false }],
    },
    sort: { price: 'asc' },
  }
}

// Item levels worth pricing a base at. Cluster jewel notable pools are gated by item
// level, and 84 is where the last tier unlocks — so an 84 base is the one that can
// roll anything, and an 83 is the cheap alternative when the target notable doesn't
// need the top tier. Anything lower isn't worth crafting on.
export const BASE_ILVLS = [83, 84] as const

// How many combos per group get priced, most-used first. scripts/price.ts defaults to
// this and the UI only looks prices up for this many, so the two stay in step.
export const PRICED_TOP = 5

// Trade query for the uncrafted base a combo is built on: same cluster type enchant
// and passive count, no notables, restricted to normal (white) rarity at one exact
// item level. Pricing this alongside the combo shows how much of the combo's price is
// the craft.
export function buildBaseQuery(
  base: string,
  clusterType: string,
  passives: PassiveRange,
  ilvl: number,
): TradeQuery | null {
  const option = clusterTypeOption(clusterType)
  if (!option) return null
  return {
    query: {
      status: { option: 'securable' },
      type: base,
      filters: {
        type_filters: { filters: { rarity: { option: 'normal' } } },
        misc_filters: {
          filters: { corrupted: { option: 'false' }, ilvl: { min: ilvl, max: ilvl } },
        },
      },
      stats: [{ type: 'and', filters: statFilter(option, passives), disabled: false }],
    },
    sort: { price: 'asc' },
  }
}

export const tradeSearchUrl = (league: string, query: TradeQuery): string =>
  `https://www.pathofexile.com/trade/search/${encodeURIComponent(league)}` +
  `?q=${encodeURIComponent(JSON.stringify(query))}`

export function comboTradeUrl(
  league: string,
  base: string,
  clusterType: string,
  cc: ComboCount,
): string | null {
  const query = buildComboQuery(base, clusterType, cc)
  return query && tradeSearchUrl(league, query)
}

export function baseTradeUrl(
  league: string,
  base: string,
  clusterType: string,
  passives: PassiveRange,
  ilvl: number,
): string | null {
  const query = buildBaseQuery(base, clusterType, passives, ilvl)
  return query && tradeSearchUrl(league, query)
}

// Cache keys for src/data/<league>/trade-prices.json. Combo prices are keyed without
// the passive range (it's derived from the combo itself); base prices include it and
// the item level, since one base + cluster type is priced separately per passive roll
// and per ilvl.
export const priceKey = (base: string, clusterType: string, combo: string): string =>
  `${base}||${clusterType}||${combo}`

export const baseKey = (
  base: string,
  clusterType: string,
  passives: PassiveRange,
  ilvl: number,
): string =>
  `${base}||${clusterType}||${passives.min ?? 'any'}-${passives.max ?? 'any'}||i${ilvl}`
